version: 2.1

orbs:
  macos: circleci/macos@2.4.0
  python: circleci/python@2.1.1
  
jobs:
  build:
    macos:
      xcode: 15.1.0
    resource_class: macos.m1.medium.gen1
    
    steps:
      - run: xcodebuild -version
      - run: brew --version
      - run: whoami
      - python/dist
      - run:
          command: |
            poetry run pytest --version
      - run: pip --version
      
      
workflows:
  say-hello-workflow:
    jobs:
      - build
