version: 2.1

orbs:
  python: circleci/python@2.1.1
  
jobs:
  build:

    executor: python/default
    
    steps:
      - checkout
      - run: whoami
      - python/install-packages:
          args: pytest
          pkg-manager: pipenv
      - run:
          command: |
            pipenv run pytest --version
          name: Test it
      - run: python --version
    
      
      
workflows:
  say-hello-workflow:
    jobs:
      - build
