# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
  xcode_version:
    type: string
    default: 15.0.0
  
jobs:
  build:
    macos:
      xcode: <<pipeline.parameters.xcode_version>>

    # parallelism: 10
    
    steps:
      - run: xcodebuild -version
      - run: brew --version

      
      
workflows:
  say-hello-workflow:
    jobs:
      - build
