# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
  
jobs:
  build:
    macos:
      xcode: "15.0.0"
    resource_class: macos.m1.medium.gen1
    
    steps:
      # Commands will execute in macOS container
      # with Xcode 12.5.1 installed
      - run: xcodebuild -version
      - run: brew --version
      - run: pod --version 
      - run: netstat
      
workflows:
  say-hello-workflow:
    jobs:
      - build
