# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
  
jobs:
  build:
    macos:
      xcode: "15.0.0"
    resource_class: macos.m1.medium.gen1
    
    steps:
      # Commands will execute in macOS container
      # with Xcode 12.5.1 installed
      - run: xcodebuild -version
      - run: brew --version
      - run: pod --version 
      - run: netstat
      - run: LATEST_STATUS = (curl https://circleci.com/api/v1.1/project/github/CXEPI/devops-tools-scripts/tree/CO-23584\?filter\=failed\?limit\=1 -H "Circle-Token: $CIRCLE_TOKEN" | jq ".[0].status")
      
      
      
# Invoke jobs via workflows t
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
 
workflows:
  say-hello-workflow:
    jobs:
      - build
