# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
  xcode_version:
    type: string
    default: 15.0.0
  
jobs:
  build:
    macos:
      xcode: <<pipeline.parameters.xcode_version>>
    resource_class: macos.m1.medium.gen1
    parallelism: 10
    
    steps:
      - run: xcodebuild -version
      - run: brew --version
      - run:
          command: |
            export SIMULATOR_UDID=$(xcrun simctl create testsim "iPhone 11" "iOS17")
            xcrun simctl boot $SIMULATOR_UDID
            xcrun simctl bootstatus $SIMULATOR_UDID
      
      
workflows:
  say-hello-workflow:
    jobs:
      - build
