version: 2.1

orbs:
  python: circleci/python@2.1.1
  
jobs:
  build:

    executor: python/default
    
    steps:
      - checkout
      - run: whoami
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: dev-requirements.txt
          pkg-manager: pip
      - python/install-packages:
          args: pytest
          pkg-manager: pip
          pypi-cache: false
      - run:
          command: |
            pytest --version
          name: Test
    
      
      
workflows:
  say-hello-workflow:
    jobs:
      - build
