# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
  
jobs:
  build:
    macos:
      xcode: "14.3.1"
    resource_class: macos.x86.medium.gen2
    
    steps:
      - run: xcodebuild -version
      - run: brew --version
      - run: pod --version 
      - run: netstat
      - run: ssh -v git@github.com
      
workflows:
  say-hello-workflow:
    jobs:
      - build
