version: 2.1

orbs:
  macos: circleci/macos@2.4.0
  
jobs:
  build:
    macos:
      xcode: 15.0.0
    resource_class: macos.m1.medium.gen1
    
    steps:
      - run: xcodebuild -version
      - run: brew --version
      - macos/add-uitest-permissions
      - macos/preboot-simulator
      - run:
          command: |
            export SIMULATOR_UDID=$(xcrun simctl create testsim "iPhone 11" "iOS15.5")
            xcrun simctl boot $SIMULATOR_UDID
            xcrun simctl bootstatus $SIMULATOR_UDID
      - run: echo $MACOS_ORB_DEVICE_UDID
      
      
workflows:
  say-hello-workflow:
    jobs:
      - build
