version: 2.1

orbs:
  macos: circleci/macos@2.4.0
  python: circleci/python@2.1.1
  
jobs:
  build:
    macos:
      xcode: 15.1.0
    resource_class: macos.x86.medium.gen2
    
    steps:
      - checkout
      - run: xcodebuild -version
      - run: brew --version
      - run: whoami
      - python/dist
      - run: pip install twine
      - run: pip --version
      
      
workflows:
  say-hello-workflow:
    jobs:
      - build
