# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
  
jobs:
  build:
    macos:
      xcode: "14.3.1"
    resource_class: macos.m1.large.gen1
    
    steps:
      # Commands will execute in macOS container
      # with Xcode 12.5.1 installed
      - run: xcodebuild -version
      - run: brew --version
      - run: pod --version 
      - run:
          name: install aws cli 
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws  
      
      
      
# Invoke jobs via workflows t
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
 
workflows:
  say-hello-workflow:
    jobs:
      - build
